/**
 * QuestaSim Integration Service
 * Ported from original GitHub project (src/services/questasimService.js)
 *
 * Desktop (Electron): spawns QuestaSim CLI via window.electronAPI
 * Web mode: gracefully degrades — shows commands for local simulation
 */

/**
 * Check if running inside Electron desktop app
 */
export function isElectron() {
  return typeof window !== "undefined" && !!window?.electronAPI;
}

/** Fetch saved QuestaSim path from user settings (stored in DB) */
export async function getStoredQuestaPath() {
  try {
    const res = await fetch("/api/settings");
    if (!res.ok) return null;
    const data = await res.json();
    return data.settings?.questasim_path || null;
  } catch {
    return null;
  }
}

/**
 * Check QuestaSim availability.
 * In Electron mode: delegates to main process.
 * In web mode: returns not-available with helpful message.
 */
export async function checkQuestasimStatus() {
  if (isElectron()) {
    try {
      const status = await window.electronAPI.checkQuestasim();
      return status;
    } catch (e) {
      return { available: false, path: null, version: null, error: e.message };
    }
  }
  // Web mode — check if user has saved a path
  const savedPath = await getStoredQuestaPath();
  return {
    available: false,
    path: savedPath,
    version: null,
    webMode: true,
    savedPath: !!savedPath,
    error:
      "QuestaSim simulation requires the desktop (Electron) version of VLSI Tracker.",
  };
}

/**
 * Run Verilog/SystemVerilog code in QuestaSim.
 * In Electron: uses IPC to spawn vsim.
 * In web: returns a structured "not available" result with guidance.
 */
export async function runInQuestasim({
  code,
  testbench = "",
  topModule = "top",
  timeout = 30000,
}) {
  if (isElectron()) {
    try {
      // Pass the user's configured path so Electron can use it
      const storedPath = await getStoredQuestaPath();
      const result = await window.electronAPI.runVSim({
        code,
        testbench,
        topModule,
        timeout,
        questasimPath: storedPath || undefined,
      });
      return result;
    } catch (e) {
      return {
        passed: false,
        output: "",
        errors: [e.message],
        log: "",
      };
    }
  }

  // Web mode — return helpful guidance
  const storedPath = await getStoredQuestaPath();
  const pathNote = storedPath
    ? `Your configured vsim.exe path: ${storedPath}`
    : "Set your vsim.exe path in Settings → QuestaSim Configuration";

  return {
    passed: false,
    output: "",
    errors: [
      "QuestaSim simulation requires the desktop (Electron) app.",
      "In web mode, use the AI Analysis feature to get feedback on your Verilog code.",
    ],
    log: "",
    webModeGuidance: [
      pathNote,
      "Compile with: vlog -sv design.sv",
      'Simulate: vsim -c top -do "run -all; quit"',
      "Or use the auto-generated Tcl script below",
    ],
  };
}

/**
 * Generate a basic testbench for a module
 * (pure JS — works in both web and Electron mode)
 */
export function generateTestbench(moduleName, ports = {}) {
  const inputs = Array.isArray(ports.inputs) ? ports.inputs : [];
  const outputs = Array.isArray(ports.outputs) ? ports.outputs : [];
  const hasClock = ports.clock || false;
  const hasReset = ports.reset || false;

  let tb = `// Auto-generated testbench for ${moduleName}\n// Generated by VLSI Tracker\n\n`;
  tb += "`timescale 1ns/1ps\n\n";
  tb += `module tb_${moduleName}();\n\n`;

  // Inputs as reg, outputs as wire
  inputs.forEach((p) => {
    const width = p.width ? `[${p.width - 1}:0] ` : "";
    tb += `  reg  ${width}${p.name};\n`;
  });
  outputs.forEach((p) => {
    const width = p.width ? `[${p.width - 1}:0] ` : "";
    tb += `  wire ${width}${p.name};\n`;
  });

  if (hasClock) {
    tb += `\n  // Clock\n  reg clk;\n  initial clk = 0;\n  always #5 clk = ~clk;\n`;
  }
  if (hasReset) {
    tb += `\n  // Reset\n  initial begin\n    rst = 1;\n    #20 rst = 0;\n  end\n`;
  }

  // DUT instantiation
  tb += `\n  // DUT\n  ${moduleName} dut (\n`;
  const allPorts = [...inputs, ...outputs];
  allPorts.forEach((p, i) => {
    tb += `    .${p.name}(${p.name})${i < allPorts.length - 1 ? "," : ""}\n`;
  });
  tb += `  );\n\n`;

  // Stimulus
  tb += `  // Stimulus\n  initial begin\n`;
  inputs.forEach((p) => {
    tb += `    ${p.name} = 0;\n`;
  });
  tb += `\n    // TODO: Add test vectors here\n    #100;\n`;
  tb += `    $display("Simulation complete");\n    $finish;\n  end\n\n`;

  // VCD dump
  tb += `  // VCD\n  initial begin\n    $dumpfile("sim.vcd");\n    $dumpvars(0, tb_${moduleName});\n  end\n\n`;
  tb += `endmodule\n`;

  return tb;
}

/**
 * Generate a QuestaSim Tcl script
 */
export function generateTclScript({
  topModule,
  codeFiles = [],
  runTime = "100ns",
  extraCommands = "",
}) {
  let tcl = `# QuestaSim Tcl Script — auto-generated by VLSI Tracker\n\n`;
  tcl += `vlib work\nvmap work work\n\n`;
  codeFiles.forEach((f) => {
    tcl += `vlog -sv "${f}"\n`;
  });
  tcl += `\nvsim work.${topModule}\n`;
  tcl += `add wave -r /*\n`;
  tcl += `run ${runTime}\n`;
  if (extraCommands) tcl += `\n${extraCommands}\n`;
  tcl += `\nquit -f\n`;
  return tcl;
}

/**
 * Parse QuestaSim output for errors and warnings
 */
export function parseQuestasimOutput(output = "") {
  if (!output) return { errors: [], warnings: [], passed: false };
  const lines = output.split("\n");
  const errors = lines.filter(
    (l) => /^\*\* Error/.test(l) || /^Error:/.test(l),
  );
  const warnings = lines.filter((l) => /^\*\* Warning/.test(l));
  const passed = errors.length === 0 && output.includes("Simulation complete");
  return { errors, warnings, passed };
}

/**
 * Get simulated CLI commands for web users (documentation/guidance)
 */
export function getSimulationCommands(
  moduleName,
  filename = "design.sv",
  vsimPath = null,
) {
  const vsim = vsimPath ? `"${vsimPath}"` : "vsim";
  const vlog = vsimPath
    ? `"${vsimPath.replace("vsim.exe", "vlog.exe")}"`
    : "vlog";
  return {
    compile: `${vlog} -sv ${filename}`,
    simulate: `${vsim} -c ${moduleName} -do "run -all; quit"`,
    full: [
      `# QuestaSim commands for ${moduleName}`,
      vsimPath
        ? `# Using: ${vsimPath}`
        : "# Make sure vsim is in PATH or set path in Settings",
      `vlib work`,
      `vmap work work`,
      `${vlog} -sv ${filename}`,
      `${vsim} -c work.${moduleName} -do "add wave -r /*; run -all; quit"`,
    ].join("\n"),
    tclBatch: `${vsim} -c -do "vlib work; vmap work work; ${vlog} -sv ${filename}; vsim work.${moduleName}; run -all; quit"`,
  };
}
